baseURL: "https://tom-schwarz.com"
languageCode: "en-us"
title: "Tom Schwarz"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "Hi, I'm Tom!"

  # Navbar Menus
  #customMenus:
  #  - name: "Blog"
  #    Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.jpg"
  name: "Tom Schwarz"
  profession: "Software Engineer at IMC Trading"
  github: "https://github.com/tomiam8"
  linkedin: "https://www.linkedin.com/in/tom-schwarz-3332b7118/"
  instagram: "https://instagram.com/tomiam8"
  facebook: "https://facebook.com/tomiam8"
    #twitter: "https://twitter.com/"

  # About
  disable_about: true
  descripe_l1_person: "Hi, I'm Tom. I'm a computer science and physics student that loves learning new things by diving in the deep end. As a student, I'm still trying to figure out what I'm interested in, but have really enjoyed algorithm design and analysis, C programming and electromagnetism courses."
  descripe_l2_person: "I've spent a while messing around trying to make cool stuff with varying levels of success. I've detailed some of the successful adventures in [projects](#projects)."
  skills: #I've disabled the skills, see layouts/partials/sections/v3/about.html to reenable
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 85
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 70

  # Experience (renamed Work & Education)
  disable_experience: false
  experience:
    - company: "IMC Trading"
      id: "IMC"
      #companyshort: "Graduate Software Engineer" #Shows up as a longer company name. Can change 'company' to be a more descriptive list term, companyfull as actual company. SET AN ID if you do this, different to the company or companyshort. Should probs refactor that whole thing to fix it, but for now the bad hack stays.
      role: "Graduate Software Engineer"
      startdate: February 2023
      enddate: Present
      featuredpoints:
        - point: Worked in Java and C++ on low latency options trading systems
    - company: "University of Sydney"
      id: "USYD"
      companyshort: "Uni tutor" #Shows up as a longer company name. Can change 'company' to be a more descriptive list term, companyfull as actual company. SET AN ID if you do this, different to the company or companyshort. Should probs refactor that whole thing to fix it, but for now the bad hack stays.
      role: "Teaching Assistant"
      startdate: March 2021
      enddate: November 2022
      featuredpoints:
        - point: Taught COMP2123 - Algorithms and Data Structures
        - point: Taught INFO113 - Object Oriented Programming
        - point: Ran a weekly tutorial class, teaching students and helping them solve problems
    - company: "USYD Physics Society"
      id: "PhySoc"
      #companyshort: "Physics Society"
      role: "President"
      startdate: October 2020
      enddate: present
      featuredpoints:
        - point: Lead society to organise, market and run events for members
        - point: Ensured society continues to support members during transition back in-person and return to lockdown over 2021

  # Education
  disable_education: false
  education:
    - degree: "B. Science / B. Advanced Studies"
      branch: "Computer Science (Honours Class 1 and the University Medal), Physics"
      university: "University of Sydney"
      startedyear: "2019"
      graduation: "2022"

  # Projects
  disable_projects: false
  projects:
    - name: "Shuffler for Spotify"
      img: /images/shuffler.png
      githublink: "https://github.com/tomiam8/shuffler-for-spotify"
      featuredlink: "https://tomiam8.github.io/shuffler-for-spotify/index.html"
      description: "Spotify's Shuffle uses advanced algorithims to play the same songs again and again. Shuffler for Spotify creates a copy of a playlist with a randomized order, that you play with shuffle off for a truly shuffled experience."
    - name: "Online Bidding Problem"
      img: /images/onlinebidding.jpg
      featuredlink: "https://drive.google.com/file/d/1OGMq4k2vHGIHoeg2FePqdGSepTsPAtFg/view?usp=sharing"
      description: "Created an algorithm to directly solve the linear programming formulation of the Online Bidding problem. Algorithm worked empirically, but ran out of time to prove correctness. More details at the linked presentation!"
    - name: "USYD Hackathon 2nd place"
      img: /images/qrtones.png
      githublink: "https://github.com/mattyhempstead/syncs-hack-2020"
      featuredlink: "https://devpost.com/software/syncs-hack-2020"
      description: "Made QR Tones, an app that encodes text to audio wave-forms, similar to QR Codes but for sound. When text is provided, the app will convert it into a tune that encodes the data that is to be transmitted. Any other device listening can decode the data and receive the text that is being transmitted. Created a somewhat working prototype."
    - name: "Droid Racing Competition"
      featuredlink: "https://photos.app.goo.gl/mGGf87a1gbboQiwf8"
      img: /images/drc.jpg
      description: "As part of the USYD robotics club, entered a computer-controlled RC car into the Droid Racing Competition as part of a team. While we didn't win, our car did complete a loop around the track!"


  # Achievements
  disable_achievements: true
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: I'm always happy to talk! Feel free to email me (or whatever communication method you prefer)!
  email: "thomaspschwarz@outlook.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false

